# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_twilio_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsms',
            name='from_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='from_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
